imap:
  host: 'imap.yandex.ru' # Адрес IMAP сервера почты.
  port: 993 # Порт IMAP сервера почты.
  login: 'user@yandex.ru' # Адрес почты.
  password: 'userpassword' # Пароль почты.
  inbox: 'INBOX' # Папка для чтения (по умолчанию для всех почтовиков папку "Входящие" = INBOX).
  archive: '' # Папка для архивирования прочтенных писем (если письма переностить не нужно, можно не указывать).
  read_only: True # True - читаем только те, что ещё не прочитанные, прсле прочтения отмечаем, как прочитанные. False - читаем все, после прочтения удаляем.

is_cycle: False # Проверка почты запускается в бесконечном цикле, каждые 60 сек.
start_bot: True # Запустить бота для приёма команд.
bot: 'token' # Указать токен бота.
my_telegram_id: 000000000 # Указать свой телеграм ID для получения сообщений.