imap:
  host: 'imap.yandex.ru' # Адрес IMAP сервера почты.
  port: 993 # Порт IMAP сервера почты.
  login: 'user@yandex.ru' # Адрес почты.
  password: 'userpassword' # Пароль почты.
  inbox: 'INBOX' # Папка для чтения (по умолчанию для всех почтовиков папку "Входящие" = INBOX).
  archive: '' # Папка для архивирования прочтенных писем (если письма переностить не нужно, можно не указывать).
  filter_from: '' # Выбрать письма только от указанного отправителя.
  filter_from_domain: '' # Выбрать письма только отправителей с указанного домена.
  read_only: True # True - читаем только те, что ещё не прочитанные, после прочтения отмечаем, как прочитанные. False - читаем все, после прочтения удаляем.

is_cycle: False # Проверка почты запускается в бесконечном цикле, каждые 60 сек.
start_bot: True # Запустить бота для приёма команд.
bot: '' # Указать токен бота (если не указано, просто будет выполняться логика без отправки в телеграм).
my_telegram_id: 000000000 # Указать свой телеграм ID для получения сообщений.
attaches_save_to: '' # Директрия для складывания вложений.
filter_ext: '' # Фильтр по расширению имени файла вложения.
backup_save_to: '' # Директрия для складывания бэкапов писем.
